# Generated by Django 4.0.6 on 2022-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
