# Generated by Django 4.0.6 on 2022-08-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_frequency_task_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.DurationField(blank=True, choices=[(3600, 'hourly'), (86400, 'daily'), (604800, 'weekly'), (18144000, 'monthly'), (217728000, 'yearly')], null=True),
        ),
    ]
